Revert "usb: gadget: configfs: Fix missing spin_lock_init()"
Our driver does not allocate a spinlock and hence initialization results in the following error during compilation:

../../../../../../kernel/sony/msm8998/drivers/usb/gadget/configfs.c: In function 'gadgets_make':
../../../../../../kernel/sony/msm8998/drivers/usb/gadget/configfs.c:1748:20: error: 'struct gadget_info' has no member named 'spinlock'

This reverts commit a501c2136bea86f0fb0bdcbe2f83eb5575798a6b.